create table agenda (
	 id_agendamento int primary key auto_increment unique,
     cpf varchar(15),
     nome varchar(90) ,
     categoria int(3),
     servico int(3) ,
     data_agendamento varchar(12) , 
     hora_agendamento int(3),
	 genero varchar(10),
     email varchar(40) not null,
     telefone varchar(15) not null,
     nome_func varchar(45),
     valor varchar (10),
     chave_de_cancelamento varchar(10) not null unique,
     cancelado varchar(5),
     data_cancelamento varchar(12),
     FOREIGN KEY (categoria)  REFERENCES categoria(id_categoria),
	 FOREIGN KEY (servico)  REFERENCES servicos(id_servico),
     FOREIGN KEY (hora_agendamento)  REFERENCES Hora(id_hora));
